export interface Producto_Terminado {
    Pt_Id? : number;
    PedExtProd_Id : number;
    Pt_Margen : number;
    Pt_PesoMillar : number;
    Pt_PesoRollo : number;
    Pt_PesoUnd : number;
    Pt_CantBolsasBulto : number;
    Pt_CantBolsasPaquete : number;
    TpSellado_Id : number;
    TpImpresion_Id : number;
    TpProd_Id : number;
    Pt_Ancho : number;
    Pt_Largo : number;
    Pt_Solapa : number;
    Prod_Id : number;
    Material_Id : number;
    Pt_Calibre : number;
    Tratado_Id : number;
    Pt_Laminado : number;
    Pigmt_Id : number;
    Pt_FuelleDer : number;
    Pt_FuelleFondo : number;
    Pt_FuelleIzq : number;
    Pt_ImpresionFD : string;
    Pt_NroEmbobinado : number;
    UndMed_ALF : string;
    UndMed_Calibre : string;
}