export interface modelBOPP{
  BOPP_Id? : number;
  BOPP_Nombre : string;
  BOPP_Descripcion : string;
  BOPP_Serial : string;
  BOPP_CantidadMicras : number;
  UndMed_Id : string;
  CatMP_Id : number;
  BOPP_Precio : number;
  TpBod_Id : number;
  BOPP_FechaIngreso : Date;
  BOPP_Ancho : number;
  BOPP_Stock : number;
  UndMed_Kg : string;
  BOPP_CantidadInicialKg : number;
  Usua_Id : number;
  BOPP_Hora : string;
  BoppGen_Id : number;
  BOPP_CodigoDoc : any,
  BOPP_TipoDoc : any,
}
