export interface modelMaquilas_Internas {
    MaqInt_Codigo : number; 
    MaqInt_Id? : number;
    MaqInt_OT : number;
    Prod_Id : number;
    Cono_Id : string;
    Ancho_Cono : number;
    Tara_Cono : number;
    Peso_Bruto : number;
    Peso_Neto : number;
    Cantidad : number;
    Presentacion : number;
    MaqInt_Medida : string;
    Maquina : number;
    Operario_Id : number;
    MaqInt_Fecha : any;
    MaqInt_Hora : string;
    Proceso_Id : string;
    Estado_Id : number;
    SvcProd_Id : number;
    MaqInt_FechaRegistro : any;
    MaqInt_HoraRegistro : string;
    Creador_Id : number;
    MaqInt_Observacion : string;
    Material_Id : number;
    Turno_Id : string;
    Impreso : boolean;
    MaqInt_ValorPago : number;
}