import { PrimeIcons, MenuItem } from 'primeng/api'
export let iconos : MenuItem[];

  iconos = [
  {label: 'Alinear al centro',  icon : PrimeIcons.ALIGN_CENTER },
  {label: 'Alinear justificar',  icon : PrimeIcons.ALIGN_JUSTIFY },
  {label: 'Alinear a la izquierda',  icon : PrimeIcons.ALIGN_LEFT },
  {label: 'Alinear a la derecha',  icon : PrimeIcons.ALIGN_RIGHT },
  {label: 'Amazonas',  icon : PrimeIcons.AMAZON },
  {label: 'Androide',  icon : PrimeIcons.ANDROID },
  {label: 'Angulo doble hacia abajo',  icon : PrimeIcons.ANGLE_DOUBLE_DOWN },
  {label: 'Angulo doble izquierdo',  icon : PrimeIcons.ANGLE_DOUBLE_LEFT },
  {label: 'Angulo doble derecho',  icon : PrimeIcons.ANGLE_DOUBLE_RIGHT },
  {label: 'Angulo doble hacia arriba',  icon : PrimeIcons.ANGLE_DOUBLE_UP },
  {label: 'Angulo hacia abajo',  icon : PrimeIcons.ANGLE_DOWN },
  {label: 'Angulo izquierdo',  icon : PrimeIcons.ANGLE_LEFT },
  {label: 'Angulo derecho',  icon : PrimeIcons.ANGLE_RIGHT },
  {label: 'Angulo hacia arriba',  icon : PrimeIcons.ANGLE_UP },
  {label: 'Manzana',  icon : PrimeIcons.APPLE },
  {label: 'Flechas alt',  icon : PrimeIcons.ARROWS_ALT },
  {label: 'Flecha círculo abajo',  icon : PrimeIcons.ARROW_CIRCLE_DOWN },
  {label: 'Flecha círculo izquierda',  icon : PrimeIcons.ARROW_CIRCLE_LEFT },
  {label: 'Flecha círculo derecha',  icon : PrimeIcons.ARROW_CIRCLE_RIGHT },
  {label: 'Fírculo de flecha arriba',  icon : PrimeIcons.ARROW_CIRCLE_UP },
  {label: 'Flecha abajo',  icon : PrimeIcons.ARROW_DOWN },
  {label: 'Flecha abajo izquierda',  icon : PrimeIcons.ARROW_DOWN_LEFT },
  {label: 'Flecha abajo derecha',  icon : PrimeIcons.ARROW_DOWN_RIGHT },
  {label: 'Flecha h',  icon : PrimeIcons.ARROW_H },
  {label: 'Flecha izquierda',  icon : PrimeIcons.ARROW_LEFT },
  {label: 'Flecha derecha',  icon : PrimeIcons.ARROW_RIGHT },
  {label: 'Flecha derecha flecha izquierda',  icon : PrimeIcons.ARROW_RIGHT_ARROW_LEFT },
  {label: 'Flecha arriba',  icon : PrimeIcons.ARROW_UP },
  {label: 'Flecha arriba izquierda',  icon : PrimeIcons.ARROW_UP_LEFT },
  {label: 'Flecha arriba a la derecha',  icon : PrimeIcons.ARROW_UP_RIGHT },
  {label: 'Flecha v',  icon : PrimeIcons.ARROW_V },
  {label: 'En',  icon : PrimeIcons.AT },
  {label: 'Hacia atrás',  icon : PrimeIcons.BACKWARD },
  {label: 'Prohibición',  icon : PrimeIcons.BAN },
  {label: 'Barras',  icon : PrimeIcons.BARS },
  {label: 'Campana',  icon : PrimeIcons.BELL },
  {label: 'Bitcoin',  icon : PrimeIcons.BITCOIN },
  {label: 'Tornillo',  icon : PrimeIcons.BOLT },
  {label: 'Libro',  icon : PrimeIcons.BOOK },
  {label: 'Marcador',  icon : PrimeIcons.BOOKMARK },
  {label: 'Llenar marcador',  icon : PrimeIcons.BOOKMARK_FILL },
  {label: 'Caja',  icon : PrimeIcons.BOX },
  {label: 'Maletín',  icon : PrimeIcons.BRIEFCASE },
  {label: 'Edificio',  icon : PrimeIcons.BUILDING },
  {label: 'Calculadora',  icon : PrimeIcons.CALCULATOR },
  {label: 'Calendario',  icon : PrimeIcons.CALENDAR },
  {label: 'Menos calendario',  icon : PrimeIcons.CALENDAR_MINUS },
  {label: 'Calendario más',  icon : PrimeIcons.CALENDAR_PLUS },
  {label: 'Horarios del calendario',  icon : PrimeIcons.CALENDAR_TIMES },
  {label: 'Cámara',  icon : PrimeIcons.CAMERA },
  {label: 'Auto',  icon : PrimeIcons.CAR },
  {label: 'Careta abajo',  icon : PrimeIcons.CARET_DOWN },
  {label: 'Careta izquierda',  icon : PrimeIcons.CARET_LEFT },
  {label: 'Careta a la derecha',  icon : PrimeIcons.CARET_RIGHT },
  {label: 'Cuidado arriba',  icon : PrimeIcons.CARET_UP },
  {label: 'Carrito más',  icon : PrimeIcons.CART_PLUS },
  {label: 'Barra gráfica',  icon : PrimeIcons.CHART_BAR },
  {label: 'Línea del carta',  icon : PrimeIcons.CHART_LINE },
  {label: 'Gráfico circular',  icon : PrimeIcons.CHART_PIE },
  {label: 'Check',  icon : PrimeIcons.CHECK },
  {label: 'Círculo de comprobación',  icon : PrimeIcons.CHECK_CIRCLE },
  {label: 'Ver cuadrado',  icon : PrimeIcons.CHECK_SQUARE },
  {label: 'Círculo de chevron hacia abajo',  icon : PrimeIcons.CHEVRON_CIRCLE_DOWN },
  {label: 'Círculo chevron izquierdo',  icon : PrimeIcons.CHEVRON_CIRCLE_LEFT },
  {label: 'Círculo de chevron a la derecha',  icon : PrimeIcons.CHEVRON_CIRCLE_RIGHT },
  {label: 'Círculo de chevron hacia arriba',  icon : PrimeIcons.CHEVRON_CIRCLE_UP },
  {label: 'Chevron abajo',  icon : PrimeIcons.CHEVRON_DOWN },
  {label: 'Chevron izquierdo',  icon : PrimeIcons.CHEVRON_LEFT },
  {label: 'Chevron derecho',  icon : PrimeIcons.CHEVRON_RIGHT },
  {label: 'Chevron arriba',  icon : PrimeIcons.CHEVRON_UP },
  {label: 'Círculo',  icon : PrimeIcons.CIRCLE },
  {label: 'Llenar círculo',  icon : PrimeIcons.CIRCLE_FILL },
  {label: 'Reloj',  icon : PrimeIcons.CLOCK },
  {label: 'clon',  icon : PrimeIcons.CLONE },
  {label: 'nube',  icon : PrimeIcons.CLOUD },
  {label: 'descarga en la nube',  icon : PrimeIcons.CLOUD_DOWNLOAD },
  {label: 'carga en la nube',  icon : PrimeIcons.CLOUD_UPLOAD },
  {label: 'código',  icon : PrimeIcons.CODE },
  {label: 'diente',  icon : PrimeIcons.COG },
  {label: 'comentario',  icon : PrimeIcons.COMMENT },
  {label: 'comentarios',  icon : PrimeIcons.COMMENTS },
  {label: 'brújula',  icon : PrimeIcons.COMPASS },
  {label: 'copiar',  icon : PrimeIcons.COPY },
  {label: 'tarjeta de crédito',  icon : PrimeIcons.CREDIT_CARD },
  {label: 'base de datos',  icon : PrimeIcons.DATABASE },
  {label: 'eliminar izquierda',  icon : PrimeIcons.DELETE_LEFT },
  {label: 'escritorio',  icon : PrimeIcons.DESKTOP },
  {label: 'direcciones',  icon : PrimeIcons.DIRECTIONS },
  {label: 'direcciones alternativas',  icon : PrimeIcons.DIRECTIONS_ALT },
  {label: 'discordia',  icon : PrimeIcons.DISCORD },
  {label: 'dólar',  icon : PrimeIcons.DOLLAR },
  {label: 'descargar',  icon : PrimeIcons.DOWNLOAD },
  {label: 'expulsar',  icon : PrimeIcons.EJECT },
  {label: 'elipsis h',  icon : PrimeIcons.ELLIPSIS_H },
  {label: 'elipsis v',  icon : PrimeIcons.ELLIPSIS_V },
  {label: 'sobre',  icon : PrimeIcons.ENVELOPE },
  {label: 'borrador',  icon : PrimeIcons.ERASER },
  {label: 'euro',  icon : PrimeIcons.EURO },
  {label: 'círculo de exclamación',  icon : PrimeIcons.EXCLAMATION_CIRCLE },
  {label: 'triángulo de exclamación',  icon : PrimeIcons.EXCLAMATION_TRIANGLE },
  {label: 'enlace externo',  icon : PrimeIcons.EXTERNAL_LINK },
  {label: 'ojo',  icon : PrimeIcons.EYE },
  {label: 'corte de ojo',  icon : PrimeIcons.EYE_SLASH },
  {label: 'facebook',  icon : PrimeIcons.FACEBOOK },
  {label: 'rápido hacia atrás',  icon : PrimeIcons.FAST_BACKWARD },
  {label: 'avance rápido',  icon : PrimeIcons.FAST_FORWARD },
  {label: 'archivo',  icon : PrimeIcons.FILE },
  {label: 'archivo de edición',  icon : PrimeIcons.FILE_EDIT },
  {label: 'archivo excel',  icon : PrimeIcons.FILE_EXCEL },
  {label: 'exportación de archivos',  icon : PrimeIcons.FILE_EXPORT },
  {label: 'importación de archivos',  icon : PrimeIcons.FILE_IMPORT },
  {label: 'archivo pdf',  icon : PrimeIcons.FILE_PDF },
  {label: 'palabra de archivo',  icon : PrimeIcons.FILE_WORD },
  {label: 'filtrar',  icon : PrimeIcons.FILTER },
  {label: 'llenado de filtro',  icon : PrimeIcons.FILTER_FILL },
  {label: 'barra de filtro',  icon : PrimeIcons.FILTER_SLASH },
  {label: 'bandera',  icon : PrimeIcons.FLAG },
  {label: 'relleno de bandera',  icon : PrimeIcons.FLAG_FILL },
  {label: 'carpeta',  icon : PrimeIcons.FOLDER },
  {label: 'carpeta abierta',  icon : PrimeIcons.FOLDER_OPEN },
  {label: 'adelante',  icon : PrimeIcons.FORWARD },
  {label: 'regalo',  icon : PrimeIcons.GIFT },
  {label: 'github',  icon : PrimeIcons.GITHUB },
  {label: 'globo',  icon : PrimeIcons.GLOBE },
  {label: 'google',  icon : PrimeIcons.GOOGLE },
  {label: 'hashtag',  icon : PrimeIcons.HASHTAG },
  {label: 'corazón',  icon : PrimeIcons.HEART },
  {label: 'llenar corazon',  icon : PrimeIcons.HEART_FILL },
  {label: 'historia',  icon : PrimeIcons.HISTORY },
  {label: 'hogar',  icon : PrimeIcons.HOME },
  {label: 'reloj de arena',  icon : PrimeIcons.HOURGLASS },
  {label: 'tarjeta de identificación',  icon : PrimeIcons.ID_CARD },
  {label: 'imagen',  icon : PrimeIcons.IMAGE },
  {label: 'imágenes',  icon : PrimeIcons.IMAGES },
  {label: 'bandeja de entrada',  icon : PrimeIcons.INBOX },
  {label: 'información',  icon : PrimeIcons.INFO },
  {label: 'círculo de información',  icon : PrimeIcons.INFO_CIRCLE },
  {label: 'instagram',  icon : PrimeIcons.INSTAGRAM },
  {label: 'llave',  icon : PrimeIcons.KEY },
  {label: 'idioma',  icon : PrimeIcons.LANGUAGE },
  {label: 'enlace',  icon : PrimeIcons.LINK },
  {label: 'linkedin',  icon : PrimeIcons.LINKEDIN },
  {label: 'lista',  icon : PrimeIcons.LIST },
  {label: 'cerrar con llave',  icon : PrimeIcons.LOCK },
  {label: 'bloqueo abierto',  icon : PrimeIcons.LOCK_OPEN },
  {label: 'mapa',  icon : PrimeIcons.MAP },
  {label: 'marcador de mapa',  icon : PrimeIcons.MAP_MARKER },
  {label: 'megáfono',  icon : PrimeIcons.MEGAPHONE },
  {label: 'micrófono',  icon : PrimeIcons.MICROPHONE },
  {label: 'microsoft',  icon : PrimeIcons.MICROSOFT },
  {label: 'menos',  icon : PrimeIcons.MINUS },
  {label: 'círculo menos',  icon : PrimeIcons.MINUS_CIRCLE },
  {label: 'móvil',  icon : PrimeIcons.MOBILE },
  {label: 'factura de dinero',  icon : PrimeIcons.MONEY_BILL },
  {label: 'luna',  icon : PrimeIcons.MOON },
  {label: 'paleta',  icon : PrimeIcons.PALETTE },
  {label: 'clip de papel',  icon : PrimeIcons.PAPERCLIP },
  {label: 'pausa',  icon : PrimeIcons.PAUSE },
  {label: 'paypal',  icon : PrimeIcons.PAYPAL },
  {label: 'lápiz',  icon : PrimeIcons.PENCIL },
  {label: 'porcentaje',  icon : PrimeIcons.PERCENTAGE },
  {label: 'teléfono',  icon : PrimeIcons.PHONE },
  {label: 'jugar',  icon : PrimeIcons.PLAY },
  {label: 'más',  icon : PrimeIcons.PLUS },
  {label: 'círculo más',  icon : PrimeIcons.PLUS_CIRCLE },
  {label: 'libra',  icon : PrimeIcons.POUND },
  {label: 'apagado',  icon : PrimeIcons.POWER_OFF },
  {label: 'principal',  icon : PrimeIcons.PRIME },
  {label: 'imprimir',  icon : PrimeIcons.PRINT },
  {label: 'código qr',  icon : PrimeIcons.QRCODE },
  {label: 'pregunta',  icon : PrimeIcons.QUESTION },
  {label: 'círculo de preguntas',  icon : PrimeIcons.QUESTION_CIRCLE },
  {label: 'reddit',  icon : PrimeIcons.REDDIT },
  {label: 'actualizar',  icon : PrimeIcons.REFRESH },
  {label: 'repetición',  icon : PrimeIcons.REPLAY },
  {label: 'responder',  icon : PrimeIcons.REPLY },
  {label: 'ahorrar',  icon : PrimeIcons.SAVE },
  {label: 'buscar',  icon : PrimeIcons.SEARCH },
  {label: 'buscar menos',  icon : PrimeIcons.SEARCH_MINUS },
  {label: 'búsqueda más',  icon : PrimeIcons.SEARCH_PLUS },
  {label: 'enviar',  icon : PrimeIcons.SEND },
  {label: 'servidor',  icon : PrimeIcons.SERVER },
  {label: 'compartir alt',  icon : PrimeIcons.SHARE_ALT },
  {label: 'blindaje',  icon : PrimeIcons.SHIELD },
  {label: 'bolsa de la compra',  icon : PrimeIcons.SHOPPING_BAG },
  {label: 'carro de la compra',  icon : PrimeIcons.SHOPPING_CART },
  {label: 'iniciar sesión',  icon : PrimeIcons.SIGN_IN },
  {label: 'desconectar',  icon : PrimeIcons.SIGN_OUT },
  {label: 'mapa del sitio',  icon : PrimeIcons.SITEMAP },
  {label: 'flojo',  icon : PrimeIcons.SLACK },
  {label: 'deslizadores h',  icon : PrimeIcons.SLIDERS_H },
  {label: 'deslizadores v',  icon : PrimeIcons.SLIDERS_V },
  {label: 'clasificar',  icon : PrimeIcons.SORT },
  {label: 'ordenar alfa alt abajo',  icon : PrimeIcons.SORT_ALPHA_ALT_DOWN },
  {label: 'ordenar alfa alt arriba',  icon : PrimeIcons.SORT_ALPHA_ALT_UP },
  {label: 'ordenar alfa hacia abajo',  icon : PrimeIcons.SORT_ALPHA_DOWN },
  {label: 'ordenar alfa hacia arriba',  icon : PrimeIcons.SORT_ALPHA_UP },
  {label: 'ordenar alt',  icon : PrimeIcons.SORT_ALT },
  {label: 'ordenar alt barra',  icon : PrimeIcons.SORT_ALT_SLASH },
  {label: 'ordenar cantidad hacia abaj',  icon : PrimeIcons.SORT_AMOUNT_DOWN}
];
